sudo: required
services:
  - docker

before_install:
  - docker build -t smalltides/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run smalltides/client-test npm test -- --coverage

after_success:
  - docker build -t smalltides/fib-client ./client
  - docker build -t smalltides/fib-nginx ./nginx
  - docker build -t smalltides/fib-server ./server
  - docker build -t smalltides/fib-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push smalltides/fib-client
  - docker push smalltides/fib-nginx
  - docker push smalltides/fib-server
  - docker push smalltides/fib-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "fib-app"
  env: "DockerFib-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-408772917132"
  bucket_path: "docker-fib"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"